export default {
  applied: [
    {
      id: 1,
      name: "guidev",
      location: "Algeria",
      contact_number: "123 456 789",
      rating: 5,
      status: "New",
      presence: "online",
      image: "https://randomuser.me/api/portraits/men/1.jpg",
    },
    {
      id: 2,
      name: "Ahmed",
      location: "Egypt",
      contact_number: "123 456 789",
      rating: 4,
      status: "New",
      presence: "offline",
      image: "https://randomuser.me/api/portraits/men/2.jpg",
    },
    {
      id: 3,
      name: "Khalid",
      location: "Morocco",
      contact_number: "123 456 789",
      rating: 3,
      status: "New",
      presence: "idle",
      image: "https://randomuser.me/api/portraits/men/3.jpg",
    },
    {
      id: 4,
      name: "Mustafa",
      location: "Jordan",
      contact_number: "123 456 789",
      rating: 5,
      status: "New",
      presence: "online",
      image: "https://randomuser.me/api/portraits/men/4.jpg",
    },
    {
      id: 5,
      name: "Youssef",
      location: "Tunisia",
      contact_number: "123 456 789",
      rating: 2,
      status: "New",
      presence: "offline",
      image: "https://randomuser.me/api/portraits/men/5.jpg",
    },
    {
      id: 6,
      name: "Ali",
      location: "Lebanon",
      contact_number: "123 456 789",
      rating: 4,
      status: "New",
      presence: "online",
      image: "https://randomuser.me/api/portraits/men/6.jpg",
    },
    {
      id: 7,
      name: "Said",
      location: "Syria",
      contact_number: "123 456 789",
      rating: 3,
      status: "New",
      presence: "idle",
      image: "https://randomuser.me/api/portraits/men/7.jpg",
    },
    {
      id: 8,
      name: "Rashid",
      location: "Iraq",
      contact_number: "123 456 789",
      rating: 2,
      status: "New",
      presence: "offline",
      image: "https://randomuser.me/api/portraits/men/8.jpg",
    },
    {
      id: 9,
      name: "Hamza",
      location: "Palestine",
      contact_number: "123 456 789",
      rating: 5,
      status: "New",
      presence: "online",
      image: "https://randomuser.me/api/portraits/men/9.jpg",
    },
    {
      id: 10,
      name: "Mahmoud",
      location: "Libya",
      contact_number: "123 456 789",
      rating: 4,
      status: "New",
      presence: "idle",
      image: "https://randomuser.me/api/portraits/men/10.jpg",
    },
  ],
  short: [
    {
      id: 11,
      name: "Mohanned",
      location: "Saudi Arabia",
      contact_number: "123 456 789",
      rating: 2,
      status: "Followed",
      presence: "idle",
      image: "https://randomuser.me/api/portraits/men/99.jpg",
    },
    {
      id: 12,
      name: "Faisal",
      location: "UAE",
      contact_number: "123 456 789",
      rating: 3,
      status: "Followed",
      presence: "offline",
      image: "https://randomuser.me/api/portraits/men/12.jpg",
    },
    {
      id: 13,
      name: "Omar",
      location: "Kuwait",
      contact_number: "123 456 789",
      rating: 4,
      status: "Followed",
      presence: "online",
      image: "https://randomuser.me/api/portraits/men/13.jpg",
    },
    {
      id: 14,
      name: "Yasin",
      location: "Bahrain",
      contact_number: "123 456 789",
      rating: 5,
      status: "Followed",
      presence: "idle",
      image: "https://randomuser.me/api/portraits/men/14.jpg",
    },
    {
      id: 15,
      name: "Jamal",
      location: "Qatar",
      contact_number: "123 456 789",
      rating: 1,
      status: "Followed",
      presence: "offline",
      image: "https://randomuser.me/api/portraits/men/15.jpg",
    },
    {
      id: 16,
      name: "Nasser",
      location: "Oman",
      contact_number: "123 456 789",
      rating: 2,
      status: "Followed",
      presence: "online",
      image: "https://randomuser.me/api/portraits/men/16.jpg",
    },
    {
      id: 17,
      name: "Abdullah",
      location: "Yemen",
      contact_number: "123 456 789",
      rating: 3,
      status: "Followed",
      presence: "idle",
      image: "https://randomuser.me/api/portraits/men/17.jpg",
    },
    {
      id: 18,
      name: "Hassan",
      location: "Sudan",
      contact_number: "123 456 789",
      rating: 4,
      status: "Followed",
      presence: "offline",
      image: "https://randomuser.me/api/portraits/men/18.jpg",
    },
    {
      id: 19,
      name: "Karim",
      location: "Jordan",
      contact_number: "123 456 789",
      rating: 5,
      status: "Followed",
      presence: "online",
      image: "https://randomuser.me/api/portraits/men/19.jpg",
    },
    {
      id: 20,
      name: "Samir",
      location: "Algeria",
      contact_number: "123 456 789",
      rating: 2,
      status: "Followed",
      presence: "idle",
      image: "https://randomuser.me/api/portraits/men/20.jpg",
    },
  ],
  interview: [
    {
      id: 21,
      name: "Seradj",
      location: "Algeria",
      contact_number: "123 456 789",
      rating: 1,
      status: "Followed",
      presence: "offline",
      image: "https://randomuser.me/api/portraits/men/21.jpg",
    },
    {
      id: 22,
      name: "Rayan",
      location: "Morocco",
      contact_number: "123 456 789",
      rating: 2,
      status: "Followed",
      presence: "online",
      image: "https://randomuser.me/api/portraits/men/22.jpg",
    },
    {
      id: 23,
      name: "Fouad",
      location: "Tunisia",
      contact_number: "123 456 789",
      rating: 3,
      status: "Followed",
      presence: "idle",
      image: "https://randomuser.me/api/portraits/men/23.jpg",
    },
    {
      id: 24,
      name: "Sami",
      location: "Lebanon",
      contact_number: "123 456 789",
      rating: 4,
      status: "Followed",
      presence: "offline",
      image: "https://randomuser.me/api/portraits/men/24.jpg",
    },
    {
      id: 25,
      name: "Bader",
      location: "Kuwait",
      contact_number: "123 456 789",
      rating: 5,
      status: "Followed",
      presence: "online",
      image: "https://randomuser.me/api/portraits/men/25.jpg",
    },
    {
      id: 26,
      name: "Saad",
      location: "UAE",
      contact_number: "123 456 789",
      rating: 2,
      status: "Followed",
      presence: "idle",
      image: "https://randomuser.me/api/portraits/men/26.jpg",
    },
    {
      id: 27,
      name: "Ibrahim",
      location: "Egypt",
      contact_number: "123 456 789",
      rating: 3,
      status: "Followed",
      presence: "offline",
      image: "https://randomuser.me/api/portraits/men/27.jpg",
    },
    {
      id: 28,
      name: "Yahya",
      location: "Saudi Arabia",
      contact_number: "123 456 789",
      rating: 4,
      status: "Followed",
      presence: "online",
      image: "https://randomuser.me/api/portraits/men/28.jpg",
    },
    {
      id: 29,
      name: "Ayman",
      location: "Qatar",
      contact_number: "123 456 789",
      rating: 1,
      status: "Followed",
      presence: "idle",
      image: "https://randomuser.me/api/portraits/men/29.jpg",
    },
    {
      id: 30,
      name: "Ziad",
      location: "Bahrain",
      contact_number: "123 456 789",
      rating: 2,
      status: "Followed",
      presence: "offline",
      image: "https://randomuser.me/api/portraits/men/30.jpg",
    },
  ],
};
